<?php
$labels = array();
$labels['gravatar_plugin'] = 'Gravatar Adressebog';
$labels['gravatar_use'] = 'Brug Gravatar';
$labels['gravatar_size'] = 'Avatar størrelse (px)';
$labels['gravatar_rating'] = 'Avatar bedømmelse';
$labels['gravatar_G'] = 'G vurdere';
$labels['gravatar_PG'] = 'PG vurdere';
$labels['gravatar_R'] = 'R vurdere';
$labels['gravatar_X'] = 'X vurdere';
$labels['gravatar_use_custom'] = 'Brug defineret API (det har altid præference)';
